# Generated by Django 3.2.8 on 2022-01-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWApp', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=150)),
                ('number', models.BigIntegerField()),
                ('address', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=5000)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
