# Generated by Django 3.2.8 on 2022-01-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWApp', '0003_sellerform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerform',
            name='comments',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='sellerform',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
