# Generated by Django 3.2.8 on 2022-01-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWApp', '0004_auto_20220108_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerform',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
