# Generated by Django 3.2.8 on 2022-01-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWApp', '0005_alter_sellerform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerform',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sellerform',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerform',
            name='comments',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='sellerform',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sellerform',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
