# Generated by Django 3.2.8 on 2022-01-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWApp', '0006_auto_20220108_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerform',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sellerform',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
