# Generated by Django 3.2.8 on 2022-01-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWApp', '0007_auto_20220108_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerform',
            name='name',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
