# Generated by Django 3.2.8 on 2022-01-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWApp', '0008_alter_sellerform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerform',
            name='comments',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
