# Generated by Django 3.2.8 on 2022-01-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWApp', '0009_alter_sellerform_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerform',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
