# Generated by Django 3.2.8 on 2022-01-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EWApp', '0010_alter_sellerform_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerform',
            name='comments',
        ),
    ]
