# Generated by Django 3.2.8 on 2022-01-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWApp', '0012_sellerform_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerform',
            name='number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sellerform',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
